# Generated by Django 5.0.1 on 2024-03-26 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caffeine', models.CharField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=50)),
                ('sugar', models.CharField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrg.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_rating', models.PositiveIntegerField(default=0)),
                ('flavor_rating', models.PositiveIntegerField(default=0)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrg.drink')),
            ],
        ),
    ]
