# Generated by Django 5.0.1 on 2024-04-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='caffeine',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
        migrations.AlterField(
            model_name='drink',
            name='sugar',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='energy_rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='flavor_rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
